version: '3.8'
services:
  db:
    image: 'mysql'
    volumes:
      # Where our data will be persisted
      - ./db:/var/lib/mysql
      # To create a second DB
      - ./init:/docker-entrypoint-initdb.d
    restart: 'always'
    expose:
      # Opens port 3306 on the container
      - '3306'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'bot'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
# Names our volume
volumes:
  mydb: